# https://rust-lang.github.io/mdBook/
[book]
title = "rust-template"
authors = ["Michael Baudler"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/mrbandler/rust-template"
edit-url-template = "https://github.com/mrbandler/rust-template/edit/main/docs/{path}"
