[package]
name = "rust-template-core"
description = "Core library of rust-template."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
miette.workspace = true
thiserror.workspace = true

[lints]
workspace = true
